# These are supported funding model platforms

github: [Leviako2025]

# Patreon
patreon:

# Open Collective
open_collective:

# Ko-fi
ko_fi:

# Tidelift
tidelift:

# Community Bridge
community_bridge:

# Liberapay
liberapay:

# IssueHunt
issuehunt:

# LFX Crowdfunding
lfx_crowdfunding:

# Polar
polar:

# Buy Me a Coffee
buy_me_a_coffee:

# thanks.dev
thanks_dev:

# Custom sponsorship URLs
custom:
